"""Tool definitions and helpers for CIPOC."""

from .extraction import (
    VariableValueValidator,
    lookup_variable_info,
    build_variable_group,
    resolve_site_key,
)
from .orchestration import (
    load_variable_groups,
    load_group_hierarchy,
    GroupNode,
    corpus_gate_passes,
    CORPUS_GATE_PREDICATES,
    evaluate_note_filter,
    note_matches_filter,
    prefilter_notes,
    build_corpus_descriptors,
    build_corpus_digests,
    site_applies,
    eligible_groups,
    pending_group,
    resolve_leftovers,
    derive_case_facts,
    not_found_results,
    to_case_results,
    build_report,
)
from .coding_context import (
    RuleStore,
    load_rule_store,
    applicable_sources,
    rules_for_items,
    matches_case,
    resolve_precedence,
    reduce_valid_codes,
    scope_coding_context,
    assemble_coding_instructions,
)

__all__ = [
    "VariableValueValidator",
    "lookup_variable_info",
    "build_variable_group",
    "resolve_site_key",
    "load_variable_groups",
    "load_group_hierarchy",
    "GroupNode",
    "corpus_gate_passes",
    "CORPUS_GATE_PREDICATES",
    "evaluate_note_filter",
    "note_matches_filter",
    "prefilter_notes",
    "build_corpus_descriptors",
    "build_corpus_digests",
    "site_applies",
    "eligible_groups",
    "pending_group",
    "resolve_leftovers",
    "derive_case_facts",
    "not_found_results",
    "to_case_results",
    "build_report",
    "RuleStore",
    "load_rule_store",
    "applicable_sources",
    "rules_for_items",
    "matches_case",
    "resolve_precedence",
    "reduce_valid_codes",
    "scope_coding_context",
    "assemble_coding_instructions",
]
