"""LLM agent prompts."""

from .extractor import (
    EXTRACTOR_SYSTEM_PROMPT,
    EXTRACT_GROUP_VALUES_PROMPT,
    EXTRACT_VARIABLE_VALUE_PROMPT,
    REPAIR_VARIABLE_VALUE_PROMPT,
)
from .note_scanner import (
    NOTE_SCANNER_SYSTEM_PROMPT,
    CANCER_IN_NOTE_PROMPT,
    NOTE_SUMMARY_PROMPT,
    CANCER_MENTIONS_PROMPT,
)

__all__ = [
    "EXTRACTOR_SYSTEM_PROMPT",
    "EXTRACT_GROUP_VALUES_PROMPT",
    "EXTRACT_VARIABLE_VALUE_PROMPT",
    "REPAIR_VARIABLE_VALUE_PROMPT",
    "NOTE_SCANNER_SYSTEM_PROMPT",
    "CANCER_IN_NOTE_PROMPT",
    "NOTE_SUMMARY_PROMPT",
    "CANCER_MENTIONS_PROMPT",
]
